confirmonquit: false
git:
  autofetch: true
  merging:
    manualcommit: false
  skiphookprefix: WIP
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never --theme="OneHalfDark"
gui:
  commitlength:
    show: true
  mouseevents: false
  scrollheight: 2
  scrollpastbottom: true
  theme:
    lightTheme: false
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - blue
reporting: "off"
splashupdatesindex: 0
startuppopupversion: 1
